stages:
  - test
  - build

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .pip

.install_requirements: &install_requirements
  - DEBIAN_FRONTEND=noninteractive apt-get update && apt-get upgrade -y
  - DEBIAN_FRONTEND=noninteractive apt-get install -y python3 python3-pip python3-rtree python3-pyproj proj-bin libproj-dev
  - pip3 install --cache-dir=.pip -r requirements.txt

verify_python:
  image: ubuntu:20.04
  stage: test
  tags:
    - group
  before_script:
    - *install_requirements
  script:
    - python3 -m compileall .

python_pycodestyle:
  image: ubuntu:20.04
  stage: test
  tags:
    - group
  before_script:
    - *install_requirements
    - pip3 install --cache-dir=.pip pycodestyle
  script:
    - pycodestyle *.py

python_pylint:
  image: ubuntu:20.04
  stage: test
  # TODO: fix code to get a better pylint rating
  allow_failure: true
  tags:
    - group
  before_script:
    - *install_requirements
    - pip3 install --cache-dir=.pip pylint
  script:
    - pylint --fail-under=8 *.py

python_black:
  image: ubuntu:20.04
  stage: test
  tags:
    - group
  before_script:
    - *install_requirements
    - pip3 install --cache-dir=.pip black==21.4b2
  script:
    - black -l 79 --check *.py

dockerbuild_latest:
  image: docker/compose:1.29.2
  stage: build
  cache: {}
  tags:
    - group
    # we need a runner with much memory to calculate the grid files
    - cuda
  script:
    - docker build -t shakyground-grid-file:latest -f Dockerfile .

    # push latest image to Docker Hub
    - docker tag shakyground-grid-file:latest gfzriesgos/shakyground-grid-file:latest
    - docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWORD}
    - docker push gfzriesgos/shakyground-grid-file:latest

    # push latest image to GitLab Container Registry
    - docker tag shakyground-grid-file:latest git.gfz-potsdam.de:5000/id2/riesgos/shakyground-grid-file:latest
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push git.gfz-potsdam.de:5000/id2/riesgos/shakyground-grid-file:latest

dockerbuild_tagged:
  image: docker/compose:1.29.2
  stage: build
  cache: {}
  tags:
    - group
    # we need a runner with much memory to calculate the grid files
    - cuda
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - docker build -t shakyground-grid-file:$CI_COMMIT_TAG -f Dockerfile .

    # push image to Docker Hub
    - docker tag shakyground-grid-file:$CI_COMMIT_TAG gfzriesgos/shakyground-grid-file:$CI_COMMIT_TAG
    - docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWORD}
    - docker push gfzriesgos/shakyground-grid-file:$CI_COMMIT_TAG

    # push image to GitLab Container Registry
    - docker tag shakyground-grid-file:$CI_COMMIT_TAG git.gfz-potsdam.de:5000/id2/riesgos/shakyground-grid-file:$CI_COMMIT_TAG
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push git.gfz-potsdam.de:5000/id2/riesgos/shakyground-grid-file:$CI_COMMIT_TAG
